---
driver:
  name: dokken
  chef_version: <%= ENV['DOKKEN_CHEF_VERSION'] || 'latest' %>

transport:
  name: dokken

provisioner:
  name: dokken
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd

  - name: ubuntu-14.04
    driver:
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update

  - name: centos-7
    driver:
      pid_one_command: /usr/lib/systemd/systemd
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd

  - name: centos-6.9
    driver:
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /bin/yum install nginx 

suites:
  - name: default
    run_list:
      - recipe[geminabox-ng::default]
    attributes:
