---
driver:
  name: dokken
  chef_version: <%= ENV['DOKKEN_CHEF_VERSION'] || 'latest' %>

transport:
  name: dokken

provisioner:
  name: dokken
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd

  - name: ubuntu-14.04
    driver:
      image: dokken/ubuntu-14.04
      pid_one_command: /sbin/init

  - name: centos-7
    attributes:
      geminabox-ng:
        run_list:
          proxy: false
    driver:
      image: dokken/centos-7
      intermediate_instructions:
        - RUN /bin/yum install -y epel-release
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd

  - name: centos-6
    attributes:
      geminabox-ng:
        run_list:
          proxy: false
    driver:
      image: dokken/centos-6
      pid_one_command: /sbin/init
      attributes:
        geminabox-ng:
          run_list:
            nginx: false

suites:
  - name: default
    run_list:
      - recipe[geminabox-ng::default]
    attributes:
