Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/unit/recipes/*_spec.rb'
    - 'spec/*/*/*_spec.rb'

Style/ExtraSpacing:
  Exclude:
    - 'attributes/default.rb'

Style/SpaceAroundOperators:
  Exclude:
    - 'attributes/default.rb'

Style/TrailingCommaInLiteral:
  Enabled: false
  Exclude:
    - 'attributes/default.rb'

Style/PercentLiteralDelimiters:
  Enabled: false
  
Lint/PercentStringArray:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false
