sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk
env:
  matrix:
  - INSTANCE=ubuntu-14
  - INSTANCE=ubuntu-16
  - INSTANCE=centos-6
  - INSTANCE=centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local unit
      - chef exec delivery local lint
      - chef exec delivery local syntax
      env: UNIT_AND_LINT=1
